SELECT academic_details_id, academic_semester, year_academic, year_of_study FROM academic_details;
SELECT address_id, street_name, street_number, post_code, city FROM address;
SELECT building_id, building_name, building_number, address_id FROM building;
SELECT classroom_id, room_number, floor, building_id FROM classroom;
SELECT classroom_enrollment_id, classroom_id, course_id FROM classroom_course;
SELECT course_id, course_name, course_date, time_start, time_end, total_hours, credits, course_type_id, course_mode_id, department_id, academic_details_id, employee_id FROM course;
SELECT course_final_location_id, course_id, mode_online_id, mode_stationary_id FROM course_final_location;
SELECT course_mode_id, mode FROM course_mode;
SELECT course_teacher_id, course_id, teacher_id FROM course_teacher;
SELECT course_type_id, course_type, course_duration FROM course_type;
SELECT degree_id, degree, department_id, degree_type_id FROM degree;
SELECT degree_type_id, degree_type FROM degree_type;
SELECT department_id, department_name, faculty_id FROM department;
SELECT employee_id, is_administrator, user_id, position_id, faculty_id FROM employee;
SELECT faculty_id, faculty_name FROM faculty;
SELECT gender_id, gender FROM gender;
SELECT mode_online_id, meeting_link, password FROM mode_online;
SELECT mode_stationary_id, classroom_id FROM mode_stationary;
SELECT position_id, name, description FROM position;
SELECT role_id, role_type FROM role;
SELECT student_id, semester, academic_year, user_id FROM student;
SELECT student_course_id, student_id, course_id FROM student_course;
SELECT student_department_id, student_id, department_id FROM student_department;
SELECT teacher_id, employee_id FROM teacher;
SELECT user_id, email_address, username, password, first_name, last_name, gender, birth_of_date, nationality, role_id, gender_id FROM `user`;


INSERT INTO academic_details(academic_details_id, academic_semester, year_academic, year_of_study) VALUES (?, ?, ?, ?);
INSERT INTO address(address_id, street_name, street_number, post_code, city) VALUES (?, ?, ?, ?, ?);
INSERT INTO building(building_id, building_name, building_number, address_id) VALUES (?, ?, ?, ?);
INSERT INTO classroom(classroom_id, room_number, floor, building_id) VALUES (?, ?, ?, ?);
INSERT INTO classroom_course(classroom_enrollment_id, classroom_id, course_id) VALUES (?, ?, ?);
INSERT INTO course(course_id, course_name, course_date, time_start, time_end, total_hours, credits, course_type_id, course_mode_id, department_id, academic_details_id, employee_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO course_final_location(course_final_location_id, course_id, mode_online_id, mode_stationary_id) VALUES (?, ?, ?, ?);
INSERT INTO course_mode(course_mode_id, mode) VALUES (?, ?);
INSERT INTO course_teacher(course_teacher_id, course_id, teacher_id) VALUES (?, ?, ?);
INSERT INTO course_type(course_type_id, course_type, course_duration) VALUES (?, ?, ?);
INSERT INTO degree(degree_id, degree, department_id, degree_type_id) VALUES (?, ?, ?, ?);
INSERT INTO degree_type(degree_type_id, degree_type) VALUES (?, ?);
INSERT INTO department(department_id, department_name, faculty_id) VALUES (?, ?, ?);
INSERT INTO employee(employee_id, is_administrator, user_id, position_id, faculty_id) VALUES (?, ?, ?, ?, ?);
INSERT INTO faculty(faculty_id, faculty_name) VALUES (?, ?);
INSERT INTO gender(gender_id, gender) VALUES (?, ?);
INSERT INTO mode_online(mode_online_id, meeting_link, password) VALUES (?, ?, ?);
INSERT INTO mode_stationary(mode_stationary_id, classroom_id) VALUES (?, ?);
INSERT INTO `position`(position_id, name, description) VALUES (?, ?, ?);
INSERT INTO role(role_id, role_type) VALUES (?, ?);
INSERT INTO student(student_id, semester, academic_year, user_id) VALUES (?, ?, ?, ?);
INSERT INTO student_course(student_course_id, student_id, course_id) VALUES (?, ?, ?);
INSERT INTO student_department(student_department_id, student_id, department_id) VALUES (?, ?, ?);
INSERT INTO teacher(teacher_id, employee_id) VALUES (?, ?);
INSERT INTO `user`(user_id, email_address, username, password, first_name, last_name, gender, birth_of_date, nationality, role_id, gender_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);


UPDATE academic_details SET academic_semester = ?, year_academic = ?, year_of_study = ? WHERE academic_details_id = ?;
UPDATE address SET street_name = ?, street_number = ?, post_code = ?, city = ? WHERE address_id = ?;
UPDATE building SET building_name = ?, building_number = ?, address_id = ? WHERE building_id = ?;
UPDATE classroom SET room_number = ?, floor = ?, building_id = ? WHERE classroom_id = ?;
UPDATE classroom_course SET classroom_id = ?, course_id = ? WHERE classroom_enrollment_id = ?;
UPDATE course SET course_name = ?, course_date = ?, time_start = ?, time_end = ?, total_hours = ?, credits = ?, course_type_id = ?, course_mode_id = ?, department_id = ?, academic_details_id = ?, employee_id = ? WHERE course_id = ?;
UPDATE course_final_location SET course_id = ?, mode_online_id = ?, mode_stationary_id = ? WHERE course_final_location_id = ?;
UPDATE course_mode SET mode = ? WHERE course_mode_id = ?;
UPDATE course_teacher SET course_id = ?, teacher_id = ?  WHERE course_teacher_id = ?;
UPDATE course_type SET course_type = ?, course_duration = ? WHERE course_type_id = ?;
UPDATE degree SET degree = ?, department_id = ?, degree_type_id = ? WHERE degree_id = ?;
UPDATE degree_type SET degree_type = ? WHERE degree_type_id = ?;
UPDATE department SET department_name = ?, faculty_id = ? WHERE department_id = ?;
UPDATE employee SET is_administrator = ?, user_id = ?, position_id = ?, faculty_id = ? WHERE employee_id = ?;
UPDATE faculty SET faculty_name = ? WHERE faculty_id = ?;
UPDATE gender SET gender = ? WHERE gender_id = ?;
UPDATE mode_online SET meeting_link = ?, password = ? WHERE mode_online_id = ?;
UPDATE mode_stationary SET classroom_id = ? WHERE mode_stationary_id = ?;
UPDATE position SET name = ?, description = ? WHERE position_id = ?;
UPDATE role SET role_type = ? WHERE role_id = ?;
UPDATE student SET semester = ?, academic_year = ?, user_id = ? WHERE student_id = ?;
UPDATE student_course SET student_id = ?, course_id = ? WHERE student_course_id = ?;
UPDATE student_department SET student_id = ?, department_id = ? WHERE student_department_id = ?;
UPDATE teacher SET employee_id = ? WHERE teacher_id = ?;
UPDATE `user` SET email_address = ?, username = ?, password = ?, first_name = ?, last_name = ?, gender = ?, birth_of_date = ?, nationality = ?, role_id = ?, gender_id = ? WHERE user_id = ?;

DELETE FROM academic_details WHERE academic_details_id = ?;
DELETE FROM address WHERE address_id = ?;
DELETE FROM building WHERE building_id = ?;
DELETE FROM classroom WHERE classroom_id = ?;
DELETE FROM classroom_course WHERE classroom_enrollment_id = ? AND classroom_id = ? AND course_id = ?;
DELETE FROM course WHERE course_id = ?;
DELETE FROM course_final_location WHERE course_final_location_id = ?;
DELETE FROM course_mode WHERE course_mode_id = ?;
DELETE FROM course_teacher WHERE course_teacher_id = ? AND course_id = ? AND teacher_id = ?;
DELETE FROM course_type WHERE course_type_id = ?;
DELETE FROM degree WHERE degree_id = ?;
DELETE FROM degree_type WHERE degree_type_id = ?;
DELETE FROM department WHERE department_id = ?;
DELETE FROM employee WHERE employee_id = ?;
DELETE FROM faculty WHERE faculty_id = ?;
DELETE FROM gender WHERE gender_id = ?;
DELETE FROM mode_online WHERE mode_online_id = ?;
DELETE FROM mode_stationary WHERE mode_stationary_id = ?;
DELETE FROM `position` WHERE position_id = ?;
DELETE FROM role WHERE role_id = ?;
DELETE FROM student WHERE student_id = ?;
DELETE FROM student_course WHERE student_course_id = ?;
DELETE FROM student_department WHERE student_department_id = ? AND student_id = ? AND department_id = ?;
DELETE FROM teacher WHERE teacher_id = ?;
DELETE FROM `user` WHERE user_id = ?;
